name: Report OTA PR
on:
    workflow_run:
        workflows: ['Check OTA PR']
        types:
            - completed

permissions:
    contents: write
    pull-requests: write

jobs:
    report-ota-pr:
        runs-on: ubuntu-latest
        # should never be anything else...
        if: |
            github.event.workflow_run.event == 'pull_request'
        steps:
            - name: Check OTA PR
              uses: actions/github-script@v7
              with:
                  script: |
                      const {reportOtaPR} = await import("${{ github.workspace }}/dist/ghw_report_ota_pr.js")

                      await reportOtaPR(github, core, context)
